### ISSUE TITLE
Wrong usage of axios API

### ISSUE THREAD

**Issue by oleg-andreyev** [catherineriver/test-task#1]
https://github.com/catherineriver/test-task/blob/922b8e5da59e381b22d329c18c857654a0f21490/src/hooks/useFetch.js#L23

Ref.: https://github.com/axios/axios#axiosconfig

**Comment by catherineriver** [comment]
@oleg-andreyev Я сюда передаю URL и метод из [компонента](https://github.com/catherineriver/test-task/blob/922b8e5da59e381b22d329c18c857654a0f21490/src/components/Auth/Auth.js#L31). Почему не правильное использование?

**Comment by oleg-andreyev** [comment]
@catherineriver исходя из документации https://github.com/axios/axios#axiosconfig когда мы используем `axios` а не `axios.get`, `axios.post` и тд. 

однако потом обратил внимание на https://github.com/axios/axios#axiosurl-config так что no longer relevant.
